# Generated by Django 5.1.7 on 2025-04-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_slug_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(),
        ),
    ]
