# Generated by Django 5.2 on 2025-05-13 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_event_slug_alter_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Date and time'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='joined_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Bycicle ride', 'Bycicle ride'), ('Skiing', 'Skiing'), ('Cinema', 'Cinema'), ('Videogames', 'Videogames'), ('Co-education', 'Co-education'), ('Theatre', 'Theatre'), ('Walk', 'Walk'), ('Sport', 'Sport'), ('Jogging', 'Jogging'), ('Restaurant', 'Restaurant'), ('Ice skating', 'Ice skating')], max_length=50, verbose_name='Event type'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=200, null=True, verbose_name='Message text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='core.event')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'ordering': ['created_at'],
            },
        ),
    ]
